import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import logging

def send_alert_email(to_email: str, subject: str, context: dict):
    smtp_email = os.getenv("SMTP_EMAIL")
    smtp_password = os.getenv("SMTP_APP_PASSWORD")

    if not smtp_email or not smtp_password:
        logging.error("SMTP credentials not found in environment variables. Email will not be sent.")
        return False

    if not to_email:
        logging.error("No recipient email configured.")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Eluno Operations <{smtp_email}>"
    msg["To"] = to_email

    order_id = context.get("order_id", "N/A")
    customer = context.get("customer", "N/A")
    store = context.get("store", "N/A")
    status = context.get("status", "N/A")
    risk_score = context.get("risk_score", "N/A")
    predicted_completion = context.get("predicted_completion", "N/A")
    root_cause = context.get("root_cause", "N/A")
    recommended_action = context.get("recommended_action", "N/A")

    text_body = f"""
Eluno Alert: High Risk Order Detected

Order ID: {order_id}
Customer: {customer}
Store: {store}
Current Status: {status}
Risk Score: {risk_score}
Predicted Completion Date: {predicted_completion}
Root Cause: {root_cause}
Recommended Action: {recommended_action}

Generated By: Eluno AI Operations Platform
"""

    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <div style="background-color: #f8d7da; padding: 20px; border-radius: 5px; border: 1px solid #f5c6cb;">
            <h2 style="color: #721c24; margin-top: 0;">Eluno Operations Alert</h2>
            <p><strong>Order ID:</strong> {order_id}</p>
            <p><strong>Customer:</strong> {customer}</p>
            <p><strong>Store:</strong> {store}</p>
            <p><strong>Current Status:</strong> {status}</p>
            <p><strong>Risk Score:</strong> <span style="color: red; font-weight: bold;">{risk_score}</span></p>
            <p><strong>Predicted Completion Date:</strong> {predicted_completion}</p>
            <hr style="border: 0; border-top: 1px solid #f5c6cb; margin: 15px 0;">
            <p><strong>Root Cause:</strong> {root_cause}</p>
            <p><strong>Recommended Action:</strong> {recommended_action}</p>
        </div>
        <p style="font-size: 12px; color: #666; margin-top: 20px;">Generated By: Eluno AI Operations Platform</p>
      </body>
    </html>
    """

    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        if smtp_password == "dummy_app_password":
            logging.info(f"[SIMULATED] Successfully sent alert email to {to_email} with subject: {subject}")
            return True
            
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(smtp_email, smtp_password)
            server.send_message(msg)
        logging.info(f"Successfully sent alert email to {to_email}")
        return True
    except Exception as e:
        logging.error(f"Failed to send email to {to_email}: {e}")
        return False
